### ISSUE TITLE
Recommended way to customize the Package

### ISSUE THREAD

**Issue by rhullah** [Sitefinity/feather-packages#119]
I'd like to be able to use the less/sass version of the package of my choice (Bootstrap in my current case).  That way I can assign the package variables (sizes, colors, font family) to what my project requires, and not have to override a lot of base css to fit project requirements.  What's the best way to do this?  

Do I need to do a `npm install` in the package directory and then tweak the variables?  If so, I'd assume I'd additionally need to manually run the grunt tasks to recompile everything, which seems a bit overkill and prone to conflicts while upgrading Feather.  Or is there a less invasive way that allows for better future upgradability.

Thanks for your help and thoughts.

**Comment by manev** [comment]
Hi rhullah,

Thank you for writing us. Basically our development process is similar to your requirements. We have added a dependency to the “bootstrap-sass” node module from which we import bootstrap’s source files into our sass files (check sitefinity.sass in assets). All of our custom sass files reside in the ‘Bootstrap\assets\src\sass’ folder. After every update to these files grunt tasks are triggered. One of the tasks is to combine all sass files into a single ‘styles.sass’ file and then convert it to a styles.css/styles.min.css. With this task we combine our sass files and the source files from Bootstrap. You could follow a similar approach. I would suggest you to create a separate package for our styles and templates (copy of Bootstrap package or the other Framework packages). For example you can call it BootstrapCustom. This is done to make sure that next time you upgrade Feather, Nuget won’t override your custom changes. When you get the latest version of Feather, NuGet will replace the files in the Bootstrap package, but the files in your custom package (BootstrapCustom) will remain intact. Then you can manually transfer the new files to your package.
As for you custom sass – you can create a folder in assets\sass, which will contain your sass files, and then reference them at the bottom of styles.css. This way you’ll be able to use all the resources, referenced before it.

**Comment by ckoch1979** [comment]
Hallo Kaloyan,

the problem, ist that the grunt file is not executing. Where in the system is the execution integrated?



Von: kaloyan manev [mailto:notifications@github.com]
Gesendet: Donnerstag, 30. April 2015 16:19
An: Sitefinity/feather-packages
Cc: Christian Koch
Betreff: Re: [feather-packages] Recommended way to customize the Package (#119)


Hi rhullah,

Thank you for writing us. Basically our development process is similar to your requirements. We have added a dependency to the “bootstrap-sass” node module from which we import bootstrap’s source files into our sass files (check sitefinity.sass in assets). All of our custom sass files reside in the ‘Bootstrap\assets\src\sass’ folder. After every update to these files grunt tasks are triggered. One of the tasks is to combine all sass files into a single ‘styles.sass’ file and then convert it to a styles.css/styles.min.css. With this task we combine our sass files and the source files from Bootstrap. You could follow a similar approach. I would suggest you to create a separate package for our styles and templates (copy of Bootstrap package or the other Framework packages). For example you can call it BootstrapCustom. This is done to make sure that next time you upgrade Feather, Nuget won’t override your custom changes. When you get the latest version of Feather, NuGet will replace the files in the Bootstrap package, but the files in your custom package (BootstrapCustom) will remain intact. Then you can manually transfer the new files to your package.
As for you custom sass – you can create a folder in assets\sass, which will contain your sass files, and then reference them at the bottom of styles.css. This way you’ll be able to use all the resources, referenced before it.

**Comment by rhullah** [comment]
@manev For clarification, what is all of the Sitefinity custom sass/images/js used for in the Bootstrap ResoucePacakge?  Is that all used for the widget designers during page edit?  Would I not need those modifications for my front end package?  Additionally, are the physical files of this repository required in the ResourcePackage directory?  I'm not fully following what all is required and what will be pulled from the Feather assembly.

**Comment by ElenaGaneva** [comment]
Hi @ckoch1979,

You can execute your grunt file by running the following commands in the console (power shell):
1)Navigate to your local folder GitHub->  feather-packages ->Bootstrap
2)Run command:
*npm install*

3)Run command:
*grunt*

@rhullah the physical files in the Resource packages folders are required in order to base your pages on package (Bootstrap, Foundation, SemanticUI). Feather automatically finds what package do you use for you pages and tries to resolve the resource files from them (js, css, cshtml, etc). If they are not found Feather will get the embedded files from the Telerik.Sitefinity.Frontend dll where they are not customized to use any frontend package. 

 Regarding your first question, I am not sure which resources do you refer? We are using all resources inside folder:
https://github.com/Sitefinity/feather-packages/tree/master/Bootstrap/assets/src  to customize MVC Feather widgets frontend depending on the Bootstrap  framework.

If you need any further clarifications on this please feel free to ask.

Regards,
Elena

**Comment by ckoch1979** [comment]
Hallo Elena,

I want to do this on my production server with the Standard Sitefinity Installation.

I’d like to make quick live changes.

Regards,
Christian


Von: Elena Ganeva [mailto:notifications@github.com]
Gesendet: Dienstag, 5. Mai 2015 13:36
An: Sitefinity/feather-packages
Cc: Christian Koch
Betreff: Re: [feather-packages] Recommended way to customize the Package (#119)


Hi @ckoch1979<https://github.com/ckoch1979>,

You can execute your grunt file by running the following commands in the console (power shell):
1)Navigate to your local folder GitHub-> feather-packages ->Bootstrap
2)Run command:
npm install

3)Run command:
grunt

@rhullah<https://github.com/rhullah> the physical files in the Resource packages folders are required in order to base your pages on package (Bootstrap, Foundation, SemanticUI). Feather automatically finds what package do you use for you pages and tries to resolve the resource files from them (js, css, cshtml, etc). If they are not found Feather will get the embedded files from the Telerik.Sitefinity.Frontend dll where they are not customized to use any frontend package.

Regarding your first question, I am not sure which resources do you refer? We are using all resources inside folder:
https://github.com/Sitefinity/feather-packages/tree/master/Bootstrap/assets/src to customize MVC Feather widgets frontend depending on the Bootstrap framework.

If you need any further clarifications on this please feel free to ask.

Regards,
Elena

**Comment by rhullah** [comment]
@ElenaGaneva The files I was asking about was the files/folders in /Bootstrap/assets/src.  What I'm wondering is that if I do indeed create a custom Package as @manev recommended, do I need to reference any assets (sass/js/images) from the system Feather-Packages to make sure out-of-the-box functionality is retained.

My worry is that if I create a custom Package so that it's layout is meets my clients needs, am I sacrificing all of the out-of-the-box functionality you guys have already provided (such as all the layouts to the widgets, or what about the SocialShare features)?  It seems like I would be, and I don't want to sacrifice all that existing functionality.

So if I want to keep all the widgets/layouts/functionality already provided, how do I best extend the css/sass for my own project needs?

**Comment by ckoch1979** [comment]
When I add the current Bootstrap Package from feather packages (Github) as a new package (simply copying it in the resource packages Folder). I get the error on the attached picture if I try to edit the template.

![bootstrap_error](https://cloud.githubusercontent.com/assets/12174524/7495061/c769908a-f40b-11e4-8ba9-7398194f653c.PNG)

**Comment by ElenaGaneva** [comment]
Hi @ckoch1979,

In case you want to make the changes on your project directly, navigate to the SitefinityWebApp\ResourcePackages\Bootstrap and run the mentioned commands there. 
Furthermore the error that you mentioned in your second post is caused because the latest feather-packages depend on changes in latest version of the product. In case you want to take advantage of the new features, I can suggest you upgrade to latest version of Feather as well.


@rhullah,

We do not provide any logic for the backend designers in these packages. In the packages we ship only styles related to the frontend widgets, so in case you don’t want to style every widget from scratch I can suggest you create new folder in ResorucePackages which copies all of the content of the Bootstrap folder and change its name only. This will preserve all existing functionality and styles and will create a new page template based on the new package that will initially look just like the existing Bootstrap page template. Then you can go to /[Custom package name]/assets/src/sass/sitefinity and edit the styles for the particular widget that you want to modify. For example if you want to make changes only to the styles of docuemntList widget, then you can go to ResourcePackages/[Custom package name]/assets/Src/sass/sitefinity /documentList and edit its content directly. This way when you need to upgrade version of Feather you will not have to worry that your changes will be deleted and you will be able to merge your changes manually. You can also create new sass file inside this folder ResourcePackages/[Custom package name]/assets/Src/sass and place your custom logic in it. Just make sure to include it in  /[Custom package name]/assets/src/sass/styles.sass file, in order to trigger this from the grunt task.

Regards,
Elena
