### ISSUE TITLE
how to add font-awesome font

### ISSUE THREAD

**Issue by mbarmettler** [Sitefinity/feather-packages#376]
i added the font files in "ResourcePackages/<project>/assets/dist/fonts"
there are also the fonts from SF and bootstrap, so i thought i can simply add the new font there and rebuild.
how do i include the font files correclty?
thank you

**Comment by JenPeleva** [comment]
Hi mbarmettler,
 
There are two possible ways to add font-awesome to your project - with or without our build infrastructure (grunt). Here are the steps for both approaches.
 
### With the Grunt Infrastrucure and font-awesome styles as scss
 
1. Add the font files to ### Bootstrap/assets/src/project/fonts (fonts is a new folder, that you create). 
 
2. Copy the font-awesome scss files and place them in ### Bootstrap/assets/src/project/sass. Import the font-awesome.scss file in ### Bootstrap/assets/src/project/main.scss. This way, after grunting the package, the font-awesome scss will be included in the main.min.css file, which is referenced in ### Bootstrap/views/layouts/default.cshtml
 
3. Run "npm install" and "grunt" in the Bootstrap project. The grunt copy task copies all font files from ### Bootstrap/assets/src/project/fonts and moves them to ### Bootstrap/assets/dist/fonts. The sass task complies all scss files, imported in ### Bootstrap/assets/src/project/main.scss, as well as the sitefinity scss and generates ### Bootstrap/assets/dist/css/main.min.css file, which is already referenced in ### Bootstrap/views/layouts/default.cshtml
 
4. Start using font-awesome on your Bootstrap pages.
 
### Without the Grunt Infrastrucure and font-awesome styles as css
 
1. Place the font-awesome fonts  in ### Bootstrap/assets/dist/fonts.
 
2. Place the ### font-awesome.min.css file in ### Bootstrap/assets/dist/css. Then reference the font-awesome css in  ### Bootstrap/views/layouts/default.cshtml (the layout file, on which all Bootstrap pages are based). 
 
4. This should be enough to use font-awesome on your Bootstrap pages. Keep in mind that in this case you should not run grunt, otherwise it will delete the changes in your dist folder.
 
Hope this helps,
Jen

**Comment by mbarmettler** [comment]
Hi Jen,

thank you very much for your input.

in my case i was missing the reference in the "default.cshtml" layout.
since i'm using my own layout file (copied the default) i was wondering why i had to add it again in default.cshtml.
since it works im glad it does - because a lot of siteifnitiy's features are a bit... hmmmmgrgrh :-)

thanks
