### ISSUE TITLE
Foundation layouts not found

### ISSUE THREAD

**Issue by konstrui** [Sitefinity/feather-packages#71]
Not sure how this works, but I only see the Bootstrap Layout Widgets inside the Toolbar. I created a new package based on Foundation and when editing my templates I would have expected the Foundation Layout Widgets?

**Comment by mariushm** [comment]
Hi Daniel,

Indeed, there is currently a limitation in our existing implementation and we only display Bootstrap grid widgets by default. In order to see the layout widgets from other packages, you should register them manually, as described in this article:
https://github.com/Sitefinity/feather/wiki/Add-customizable-grid-controls-based-on-simple-HTML

Please note that we are currently working on an improvement, which will register automatically all layout widgets existing in ResourcePackages\[some package]\GridSystem\Templates

Mariush

**Comment by konstrui** [comment]
Thanks.

**Comment by mariushm** [comment]
Hi Daniel,

We just shipped this weeks version with a fix to the issue in question. Enjoy!

Mariush

**Comment by konstrui** [comment]
Great! Thanks.
